<?xml version="1.0"?>
<robot name="pi_car" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:property name="base_length" value="0.14"/> 
  <xacro:property name="base_width"  value="0.18"/> 
  <xacro:property name="base_height" value="0.09"/> 

  <xacro:property name="wheel_radius" value="0.0325"/> 
  <xacro:property name="wheel_width"  value="0.02"/>
  <xacro:property name="wheel_off_z"  value="-0.02"/> 
  
  <xacro:property name="wheel_off_x"  value="0.045"/> 

  <xacro:property name="lidar_radius" value="0.035"/>
  <xacro:property name="lidar_height" value="0.03"/>
  <xacro:property name="lidar_off_x"  value="0.0"/>   
  
  <xacro:property name="standoff_height" value="0.085"/> 

  <material name="blue"> <color rgba="0 0 0.8 1"/> </material>
  <material name="black"> <color rgba="0 0 0 1"/> </material>
  <material name="white"> <color rgba="1 1 1 1"/> </material>
  <material name="gold"> <color rgba="1 0.84 0 1"/> </material>

  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 50" rpy="0 0 0"/>
  </joint>

  <link name="base_link">
    <visual>
      <origin xyz="0 0 0.06" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
  </link>

  <xacro:macro name="wheel" params="prefix reflect_y x_offset">
    <link name="${prefix}_wheel_link">
      <visual>
        <origin xyz="0 0 0.06" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
    </link>

    <joint name="${prefix}_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_wheel_link"/>
      <origin xyz="${x_offset} ${reflect_y*(base_width/2 + wheel_width/2)} ${wheel_off_z}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <xacro:wheel prefix="front_left"  reflect_y="1"  x_offset="${wheel_off_x}"/>
  <xacro:wheel prefix="front_right" reflect_y="-1" x_offset="${wheel_off_x}"/>
  <xacro:wheel prefix="rear_left"   reflect_y="1"  x_offset="-${wheel_off_x}"/>
  <xacro:wheel prefix="rear_right"  reflect_y="-1" x_offset="-${wheel_off_x}"/>

  <link name="standoff_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.005" length="${standoff_height}"/>
      </geometry>
      <material name="gold"/>
    </visual>
  </link>

  <joint name="standoff_joint" type="fixed">
    <parent link="base_link"/>
    <child link="standoff_link"/>
    <origin xyz="${lidar_off_x} 0 ${base_height/2 + standoff_height/2}" rpy="0 0 0"/>
  </joint>

  <link name="laser">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${lidar_radius}" length="${lidar_height}"/>
      </geometry>
      <material name="black"/>
    </visual>
  </link>

  <joint name="laser_joint" type="fixed">
    <parent link="base_link"/>
    <child link="laser"/>
    <origin xyz="${lidar_off_x} 0 ${base_height/2 + standoff_height + lidar_height/2}" rpy="0 0 0"/>
  </joint>

</robot>
