slam_toolbox:
  ros__parameters:
    # 1. 핵심: 프레임 이름 맞추기
    odom_frame: odom
    map_frame: map
    base_frame: base_link  # <--- 여기가 중요합니다! (기본값 base_footprint -> base_link로 변경)
    scan_topic: /scan

    # 2. 성능 최적화 (Pi 5에 맞춤)
    mode: mapping
    map_update_interval: 0.1
    resolution: 0.05
    max_laser_range: 12.0
    
    # 3. 알고리즘 설정 (CeresSolver 사용)
    solver_plugin: solver_plugins::CeresSolver
    solver_options:
      iterative_refinement_max_passes: 3
